### ISSUE TITLE
Location of run_test scripts

### ISSUE THREAD

**Issue by jiang719** [nus-apr/cerberus#130]
Hi

For the APR competition, where can we find the scripts from the docker container of our tool? The comments say that `self.dir_setup` is the directory to access setup scripts, but when I try to run the tool with bug-1 in Defects4J, I cannot find the scripts in the `dir_setup`:
bash: /setup/defects4j/Chart/Chart-1/run_test: No such file or directory

here `/setup/defects4j/Chart/Chart-1/` is the `dir_setup`

Are we supposed to find these scripts such as run_test somewhere?

**Comment by rshariffdeen** [comment]
Hi,
The repair driver will be provided with the script name, you can access this information using the following code
```
test_script_name = bug_info.get(self.key_test_script, None)
test_script = join(self.dir_setup, test_script_name)
``` 
Note that we have not implemented the test-script for Defects4J since it already has a interface to invoke the test. 
Please use the test-benchmarks we have created to test your tool integrations

Functional Java: `https://github.com/APR-Comp/functional-java` alias `aprcompfuncjava` in Cerberus
AI Errors Java: `https://github.com/APR-Comp/autocode-java/` alias `aprcompaijava` in Cerberus
